// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: BlueSDK.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum BlueDeviceType: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case bluetoothDevice // = 1
  case uwbdevice // = 2

  public init() {
    self = .bluetoothDevice
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 1: self = .bluetoothDevice
    case 2: self = .uwbdevice
    default: return nil
    }
  }

  public var rawValue: Int {
    switch self {
    case .bluetoothDevice: return 1
    case .uwbdevice: return 2
    }
  }

}

#if swift(>=4.2)

extension BlueDeviceType: CaseIterable {
  // Support synthesized by the compiler.
}

#endif  // swift(>=4.2)

public enum BlueRefreshOssSoCredentialStatus: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case succeeded // = 1
  case failed // = 2
  case notNeeded // = 3
  case unsupported // = 4

  public init() {
    self = .succeeded
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 1: self = .succeeded
    case 2: self = .failed
    case 3: self = .notNeeded
    case 4: self = .unsupported
    default: return nil
    }
  }

  public var rawValue: Int {
    switch self {
    case .succeeded: return 1
    case .failed: return 2
    case .notNeeded: return 3
    case .unsupported: return 4
    }
  }

}

#if swift(>=4.2)

extension BlueRefreshOssSoCredentialStatus: CaseIterable {
  // Support synthesized by the compiler.
}

#endif  // swift(>=4.2)

public struct BlueI18n {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var nfcWaitMessage: String {
    get {return _nfcWaitMessage ?? "Waiting for transponder"}
    set {_nfcWaitMessage = newValue}
  }
  /// Returns true if `nfcWaitMessage` has been explicitly set.
  public var hasNfcWaitMessage: Bool {return self._nfcWaitMessage != nil}
  /// Clears the value of `nfcWaitMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcWaitMessage() {self._nfcWaitMessage = nil}

  public var nfcOssSuccessReadConfigurationMessage: String {
    get {return _nfcOssSuccessReadConfigurationMessage ?? "Configuration read successfully"}
    set {_nfcOssSuccessReadConfigurationMessage = newValue}
  }
  /// Returns true if `nfcOssSuccessReadConfigurationMessage` has been explicitly set.
  public var hasNfcOssSuccessReadConfigurationMessage: Bool {return self._nfcOssSuccessReadConfigurationMessage != nil}
  /// Clears the value of `nfcOssSuccessReadConfigurationMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcOssSuccessReadConfigurationMessage() {self._nfcOssSuccessReadConfigurationMessage = nil}

  public var nfcOssSuccessUpdateConfigurationMessage: String {
    get {return _nfcOssSuccessUpdateConfigurationMessage ?? "Configuration successfully updated"}
    set {_nfcOssSuccessUpdateConfigurationMessage = newValue}
  }
  /// Returns true if `nfcOssSuccessUpdateConfigurationMessage` has been explicitly set.
  public var hasNfcOssSuccessUpdateConfigurationMessage: Bool {return self._nfcOssSuccessUpdateConfigurationMessage != nil}
  /// Clears the value of `nfcOssSuccessUpdateConfigurationMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcOssSuccessUpdateConfigurationMessage() {self._nfcOssSuccessUpdateConfigurationMessage = nil}

  public var nfcOssSuccessClearEventsMessage: String {
    get {return _nfcOssSuccessClearEventsMessage ?? "Events successfully cleared"}
    set {_nfcOssSuccessClearEventsMessage = newValue}
  }
  /// Returns true if `nfcOssSuccessClearEventsMessage` has been explicitly set.
  public var hasNfcOssSuccessClearEventsMessage: Bool {return self._nfcOssSuccessClearEventsMessage != nil}
  /// Clears the value of `nfcOssSuccessClearEventsMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcOssSuccessClearEventsMessage() {self._nfcOssSuccessClearEventsMessage = nil}

  public var nfcOssSuccessIsProvisionedMessage: String {
    get {return _nfcOssSuccessIsProvisionedMessage ?? "Is already provisioned"}
    set {_nfcOssSuccessIsProvisionedMessage = newValue}
  }
  /// Returns true if `nfcOssSuccessIsProvisionedMessage` has been explicitly set.
  public var hasNfcOssSuccessIsProvisionedMessage: Bool {return self._nfcOssSuccessIsProvisionedMessage != nil}
  /// Clears the value of `nfcOssSuccessIsProvisionedMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcOssSuccessIsProvisionedMessage() {self._nfcOssSuccessIsProvisionedMessage = nil}

  public var nfcOssSuccessProvisionMessage: String {
    get {return _nfcOssSuccessProvisionMessage ?? "Successfully provisioned"}
    set {_nfcOssSuccessProvisionMessage = newValue}
  }
  /// Returns true if `nfcOssSuccessProvisionMessage` has been explicitly set.
  public var hasNfcOssSuccessProvisionMessage: Bool {return self._nfcOssSuccessProvisionMessage != nil}
  /// Clears the value of `nfcOssSuccessProvisionMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcOssSuccessProvisionMessage() {self._nfcOssSuccessProvisionMessage = nil}

  public var nfcOssSuccessUnprovisionMessage: String {
    get {return _nfcOssSuccessUnprovisionMessage ?? "Successfully unprovisioned"}
    set {_nfcOssSuccessUnprovisionMessage = newValue}
  }
  /// Returns true if `nfcOssSuccessUnprovisionMessage` has been explicitly set.
  public var hasNfcOssSuccessUnprovisionMessage: Bool {return self._nfcOssSuccessUnprovisionMessage != nil}
  /// Clears the value of `nfcOssSuccessUnprovisionMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcOssSuccessUnprovisionMessage() {self._nfcOssSuccessUnprovisionMessage = nil}

  public var nfcOssSuccessFormatMessage: String {
    get {return _nfcOssSuccessFormatMessage ?? "Transponder was successfully formatted"}
    set {_nfcOssSuccessFormatMessage = newValue}
  }
  /// Returns true if `nfcOssSuccessFormatMessage` has been explicitly set.
  public var hasNfcOssSuccessFormatMessage: Bool {return self._nfcOssSuccessFormatMessage != nil}
  /// Clears the value of `nfcOssSuccessFormatMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcOssSuccessFormatMessage() {self._nfcOssSuccessFormatMessage = nil}

  public var cmnCancelLabel: String {
    get {return _cmnCancelLabel ?? "Cancel"}
    set {_cmnCancelLabel = newValue}
  }
  /// Returns true if `cmnCancelLabel` has been explicitly set.
  public var hasCmnCancelLabel: Bool {return self._cmnCancelLabel != nil}
  /// Clears the value of `cmnCancelLabel`. Subsequent reads from it will return its default value.
  public mutating func clearCmnCancelLabel() {self._cmnCancelLabel = nil}

  public var openViaOssTitle: String {
    get {return _openViaOssTitle ?? "Unlocking the device"}
    set {_openViaOssTitle = newValue}
  }
  /// Returns true if `openViaOssTitle` has been explicitly set.
  public var hasOpenViaOssTitle: Bool {return self._openViaOssTitle != nil}
  /// Clears the value of `openViaOssTitle`. Subsequent reads from it will return its default value.
  public mutating func clearOpenViaOssTitle() {self._openViaOssTitle = nil}

  public var openViaOssWaitMessage: String {
    get {return _openViaOssWaitMessage ?? "Please wait..."}
    set {_openViaOssWaitMessage = newValue}
  }
  /// Returns true if `openViaOssWaitMessage` has been explicitly set.
  public var hasOpenViaOssWaitMessage: Bool {return self._openViaOssWaitMessage != nil}
  /// Clears the value of `openViaOssWaitMessage`. Subsequent reads from it will return its default value.
  public mutating func clearOpenViaOssWaitMessage() {self._openViaOssWaitMessage = nil}

  public var openViaOssSuccessfulMessage: String {
    get {return _openViaOssSuccessfulMessage ?? "Successfully unlocked"}
    set {_openViaOssSuccessfulMessage = newValue}
  }
  /// Returns true if `openViaOssSuccessfulMessage` has been explicitly set.
  public var hasOpenViaOssSuccessfulMessage: Bool {return self._openViaOssSuccessfulMessage != nil}
  /// Clears the value of `openViaOssSuccessfulMessage`. Subsequent reads from it will return its default value.
  public mutating func clearOpenViaOssSuccessfulMessage() {self._openViaOssSuccessfulMessage = nil}

  public var openViaOssUnsuccessfulMessage: String {
    get {return _openViaOssUnsuccessfulMessage ?? "Unsuccessfully unlocked"}
    set {_openViaOssUnsuccessfulMessage = newValue}
  }
  /// Returns true if `openViaOssUnsuccessfulMessage` has been explicitly set.
  public var hasOpenViaOssUnsuccessfulMessage: Bool {return self._openViaOssUnsuccessfulMessage != nil}
  /// Clears the value of `openViaOssUnsuccessfulMessage`. Subsequent reads from it will return its default value.
  public mutating func clearOpenViaOssUnsuccessfulMessage() {self._openViaOssUnsuccessfulMessage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _nfcWaitMessage: String? = nil
  fileprivate var _nfcOssSuccessReadConfigurationMessage: String? = nil
  fileprivate var _nfcOssSuccessUpdateConfigurationMessage: String? = nil
  fileprivate var _nfcOssSuccessClearEventsMessage: String? = nil
  fileprivate var _nfcOssSuccessIsProvisionedMessage: String? = nil
  fileprivate var _nfcOssSuccessProvisionMessage: String? = nil
  fileprivate var _nfcOssSuccessUnprovisionMessage: String? = nil
  fileprivate var _nfcOssSuccessFormatMessage: String? = nil
  fileprivate var _cmnCancelLabel: String? = nil
  fileprivate var _openViaOssTitle: String? = nil
  fileprivate var _openViaOssWaitMessage: String? = nil
  fileprivate var _openViaOssSuccessfulMessage: String? = nil
  fileprivate var _openViaOssUnsuccessfulMessage: String? = nil
}

public struct BlueDeviceDetailsBluetooth {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var rssi: Int32 {
    get {return _rssi ?? 0}
    set {_rssi = newValue}
  }
  /// Returns true if `rssi` has been explicitly set.
  public var hasRssi: Bool {return self._rssi != nil}
  /// Clears the value of `rssi`. Subsequent reads from it will return its default value.
  public mutating func clearRssi() {self._rssi = nil}

  public var txPower: Int32 {
    get {return _txPower ?? 0}
    set {_txPower = newValue}
  }
  /// Returns true if `txPower` has been explicitly set.
  public var hasTxPower: Bool {return self._txPower != nil}
  /// Clears the value of `txPower`. Subsequent reads from it will return its default value.
  public mutating func clearTxPower() {self._txPower = nil}

  public var isIbeacon: Bool {
    get {return _isIbeacon ?? false}
    set {_isIbeacon = newValue}
  }
  /// Returns true if `isIbeacon` has been explicitly set.
  public var hasIsIbeacon: Bool {return self._isIbeacon != nil}
  /// Clears the value of `isIbeacon`. Subsequent reads from it will return its default value.
  public mutating func clearIsIbeacon() {self._isIbeacon = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _rssi: Int32? = nil
  fileprivate var _txPower: Int32? = nil
  fileprivate var _isIbeacon: Bool? = nil
}

public struct BlueDeviceDetailsUWB {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var notUsed: Bool {
    get {return _notUsed ?? false}
    set {_notUsed = newValue}
  }
  /// Returns true if `notUsed` has been explicitly set.
  public var hasNotUsed: Bool {return self._notUsed != nil}
  /// Clears the value of `notUsed`. Subsequent reads from it will return its default value.
  public mutating func clearNotUsed() {self._notUsed = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _notUsed: Bool? = nil
}

public struct BlueDeviceInfo {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceType: BlueDeviceType {
    get {return _deviceType ?? .bluetoothDevice}
    set {_deviceType = newValue}
  }
  /// Returns true if `deviceType` has been explicitly set.
  public var hasDeviceType: Bool {return self._deviceType != nil}
  /// Clears the value of `deviceType`. Subsequent reads from it will return its default value.
  public mutating func clearDeviceType() {self._deviceType = nil}

  public var deviceID: String {
    get {return _deviceID ?? String()}
    set {_deviceID = newValue}
  }
  /// Returns true if `deviceID` has been explicitly set.
  public var hasDeviceID: Bool {return self._deviceID != nil}
  /// Clears the value of `deviceID`. Subsequent reads from it will return its default value.
  public mutating func clearDeviceID() {self._deviceID = nil}

  public var distanceMeters: Float {
    get {return _distanceMeters ?? 0}
    set {_distanceMeters = newValue}
  }
  /// Returns true if `distanceMeters` has been explicitly set.
  public var hasDistanceMeters: Bool {return self._distanceMeters != nil}
  /// Clears the value of `distanceMeters`. Subsequent reads from it will return its default value.
  public mutating func clearDistanceMeters() {self._distanceMeters = nil}

  public var manufacturerInfo: BlueBleManufacturerInfo {
    get {return _manufacturerInfo ?? BlueBleManufacturerInfo()}
    set {_manufacturerInfo = newValue}
  }
  /// Returns true if `manufacturerInfo` has been explicitly set.
  public var hasManufacturerInfo: Bool {return self._manufacturerInfo != nil}
  /// Clears the value of `manufacturerInfo`. Subsequent reads from it will return its default value.
  public mutating func clearManufacturerInfo() {self._manufacturerInfo = nil}

  public var details: BlueDeviceInfo.OneOf_Details? = nil

  public var bluetooth: BlueDeviceDetailsBluetooth {
    get {
      if case .bluetooth(let v)? = details {return v}
      return BlueDeviceDetailsBluetooth()
    }
    set {details = .bluetooth(newValue)}
  }

  public var uwb: BlueDeviceDetailsUWB {
    get {
      if case .uwb(let v)? = details {return v}
      return BlueDeviceDetailsUWB()
    }
    set {details = .uwb(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Details: Equatable {
    case bluetooth(BlueDeviceDetailsBluetooth)
    case uwb(BlueDeviceDetailsUWB)

    fileprivate var isInitialized: Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch self {
      case .bluetooth: return {
        guard case .bluetooth(let v) = self else { preconditionFailure() }
        return v.isInitialized
      }()
      case .uwb: return {
        guard case .uwb(let v) = self else { preconditionFailure() }
        return v.isInitialized
      }()
      }
    }

  #if !swift(>=4.1)
    public static func ==(lhs: BlueDeviceInfo.OneOf_Details, rhs: BlueDeviceInfo.OneOf_Details) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.bluetooth, .bluetooth): return {
        guard case .bluetooth(let l) = lhs, case .bluetooth(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.uwb, .uwb): return {
        guard case .uwb(let l) = lhs, case .uwb(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  public init() {}

  fileprivate var _deviceType: BlueDeviceType? = nil
  fileprivate var _deviceID: String? = nil
  fileprivate var _distanceMeters: Float? = nil
  fileprivate var _manufacturerInfo: BlueBleManufacturerInfo? = nil
}

public struct BlueAccessCredential {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var credentialID: BlueCredentialId {
    get {return _storage._credentialID ?? BlueCredentialId()}
    set {_uniqueStorage()._credentialID = newValue}
  }
  /// Returns true if `credentialID` has been explicitly set.
  public var hasCredentialID: Bool {return _storage._credentialID != nil}
  /// Clears the value of `credentialID`. Subsequent reads from it will return its default value.
  public mutating func clearCredentialID() {_uniqueStorage()._credentialID = nil}

  public var credentialType: BlueCredentialType {
    get {return _storage._credentialType ?? .regular}
    set {_uniqueStorage()._credentialType = newValue}
  }
  /// Returns true if `credentialType` has been explicitly set.
  public var hasCredentialType: Bool {return _storage._credentialType != nil}
  /// Clears the value of `credentialType`. Subsequent reads from it will return its default value.
  public mutating func clearCredentialType() {_uniqueStorage()._credentialType = nil}

  public var name: String {
    get {return _storage._name ?? String()}
    set {_uniqueStorage()._name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {return _storage._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {_uniqueStorage()._name = nil}

  public var description_p: String {
    get {return _storage._description_p ?? String()}
    set {_uniqueStorage()._description_p = newValue}
  }
  /// Returns true if `description_p` has been explicitly set.
  public var hasDescription_p: Bool {return _storage._description_p != nil}
  /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
  public mutating func clearDescription_p() {_uniqueStorage()._description_p = nil}

  public var siteID: Int32 {
    get {return _storage._siteID ?? 0}
    set {_uniqueStorage()._siteID = newValue}
  }
  /// Returns true if `siteID` has been explicitly set.
  public var hasSiteID: Bool {return _storage._siteID != nil}
  /// Clears the value of `siteID`. Subsequent reads from it will return its default value.
  public mutating func clearSiteID() {_uniqueStorage()._siteID = nil}

  public var siteName: String {
    get {return _storage._siteName ?? String()}
    set {_uniqueStorage()._siteName = newValue}
  }
  /// Returns true if `siteName` has been explicitly set.
  public var hasSiteName: Bool {return _storage._siteName != nil}
  /// Clears the value of `siteName`. Subsequent reads from it will return its default value.
  public mutating func clearSiteName() {_uniqueStorage()._siteName = nil}

  public var validFrom: BlueLocalTimestamp {
    get {return _storage._validFrom ?? BlueLocalTimestamp()}
    set {_uniqueStorage()._validFrom = newValue}
  }
  /// Returns true if `validFrom` has been explicitly set.
  public var hasValidFrom: Bool {return _storage._validFrom != nil}
  /// Clears the value of `validFrom`. Subsequent reads from it will return its default value.
  public mutating func clearValidFrom() {_uniqueStorage()._validFrom = nil}

  public var validTo: BlueLocalTimestamp {
    get {return _storage._validTo ?? BlueLocalTimestamp()}
    set {_uniqueStorage()._validTo = newValue}
  }
  /// Returns true if `validTo` has been explicitly set.
  public var hasValidTo: Bool {return _storage._validTo != nil}
  /// Clears the value of `validTo`. Subsequent reads from it will return its default value.
  public mutating func clearValidTo() {_uniqueStorage()._validTo = nil}

  public var validity: BlueLocalTimestamp {
    get {return _storage._validity ?? BlueLocalTimestamp()}
    set {_uniqueStorage()._validity = newValue}
  }
  /// Returns true if `validity` has been explicitly set.
  public var hasValidity: Bool {return _storage._validity != nil}
  /// Clears the value of `validity`. Subsequent reads from it will return its default value.
  public mutating func clearValidity() {_uniqueStorage()._validity = nil}

  public var privateKey: Data {
    get {return _storage._privateKey ?? Data()}
    set {_uniqueStorage()._privateKey = newValue}
  }
  /// Returns true if `privateKey` has been explicitly set.
  public var hasPrivateKey: Bool {return _storage._privateKey != nil}
  /// Clears the value of `privateKey`. Subsequent reads from it will return its default value.
  public mutating func clearPrivateKey() {_uniqueStorage()._privateKey = nil}

  public var receiverName: String {
    get {return _storage._receiverName ?? String()}
    set {_uniqueStorage()._receiverName = newValue}
  }
  /// Returns true if `receiverName` has been explicitly set.
  public var hasReceiverName: Bool {return _storage._receiverName != nil}
  /// Clears the value of `receiverName`. Subsequent reads from it will return its default value.
  public mutating func clearReceiverName() {_uniqueStorage()._receiverName = nil}

  public var organisation: String {
    get {return _storage._organisation ?? String()}
    set {_uniqueStorage()._organisation = newValue}
  }
  /// Returns true if `organisation` has been explicitly set.
  public var hasOrganisation: Bool {return _storage._organisation != nil}
  /// Clears the value of `organisation`. Subsequent reads from it will return its default value.
  public mutating func clearOrganisation() {_uniqueStorage()._organisation = nil}

  public var organisationName: String {
    get {return _storage._organisationName ?? String()}
    set {_uniqueStorage()._organisationName = newValue}
  }
  /// Returns true if `organisationName` has been explicitly set.
  public var hasOrganisationName: Bool {return _storage._organisationName != nil}
  /// Clears the value of `organisationName`. Subsequent reads from it will return its default value.
  public mutating func clearOrganisationName() {_uniqueStorage()._organisationName = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct BlueAccessCredentialList {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var credentials: [BlueAccessCredential] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct BlueAccessDevice {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceID: String {
    get {return _deviceID ?? String()}
    set {_deviceID = newValue}
  }
  /// Returns true if `deviceID` has been explicitly set.
  public var hasDeviceID: Bool {return self._deviceID != nil}
  /// Clears the value of `deviceID`. Subsequent reads from it will return its default value.
  public mutating func clearDeviceID() {self._deviceID = nil}

  public var objectName: String {
    get {return _objectName ?? String()}
    set {_objectName = newValue}
  }
  /// Returns true if `objectName` has been explicitly set.
  public var hasObjectName: Bool {return self._objectName != nil}
  /// Clears the value of `objectName`. Subsequent reads from it will return its default value.
  public mutating func clearObjectName() {self._objectName = nil}

  public var objectID: Int32 {
    get {return _objectID ?? 0}
    set {_objectID = newValue}
  }
  /// Returns true if `objectID` has been explicitly set.
  public var hasObjectID: Bool {return self._objectID != nil}
  /// Clears the value of `objectID`. Subsequent reads from it will return its default value.
  public mutating func clearObjectID() {self._objectID = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _deviceID: String? = nil
  fileprivate var _objectName: String? = nil
  fileprivate var _objectID: Int32? = nil
}

public struct BlueAccessDeviceList {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var devices: [BlueAccessDevice] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct BlueAccessObject {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String {
    get {return _id ?? String()}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  public var hasID: Bool {return self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  public mutating func clearID() {self._id = nil}

  public var objectID: Int32 {
    get {return _objectID ?? 0}
    set {_objectID = newValue}
  }
  /// Returns true if `objectID` has been explicitly set.
  public var hasObjectID: Bool {return self._objectID != nil}
  /// Clears the value of `objectID`. Subsequent reads from it will return its default value.
  public mutating func clearObjectID() {self._objectID = nil}

  public var name: String {
    get {return _name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {return self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {self._name = nil}

  public var description_p: String {
    get {return _description_p ?? String()}
    set {_description_p = newValue}
  }
  /// Returns true if `description_p` has been explicitly set.
  public var hasDescription_p: Bool {return self._description_p != nil}
  /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
  public mutating func clearDescription_p() {self._description_p = nil}

  public var deviceIds: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _id: String? = nil
  fileprivate var _objectID: Int32? = nil
  fileprivate var _name: String? = nil
  fileprivate var _description_p: String? = nil
}

public struct BlueAccessObjectList {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var objects: [BlueAccessObject] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct BlueRefreshOssSoCredential {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var credentialID: BlueCredentialId {
    get {return _credentialID ?? BlueCredentialId()}
    set {_credentialID = newValue}
  }
  /// Returns true if `credentialID` has been explicitly set.
  public var hasCredentialID: Bool {return self._credentialID != nil}
  /// Clears the value of `credentialID`. Subsequent reads from it will return its default value.
  public mutating func clearCredentialID() {self._credentialID = nil}

  public var status: BlueRefreshOssSoCredentialStatus {
    get {return _status ?? .succeeded}
    set {_status = newValue}
  }
  /// Returns true if `status` has been explicitly set.
  public var hasStatus: Bool {return self._status != nil}
  /// Clears the value of `status`. Subsequent reads from it will return its default value.
  public mutating func clearStatus() {self._status = nil}

  public var configuration: BlueOssSoConfiguration {
    get {return _configuration ?? BlueOssSoConfiguration()}
    set {_configuration = newValue}
  }
  /// Returns true if `configuration` has been explicitly set.
  public var hasConfiguration: Bool {return self._configuration != nil}
  /// Clears the value of `configuration`. Subsequent reads from it will return its default value.
  public mutating func clearConfiguration() {self._configuration = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _credentialID: BlueCredentialId? = nil
  fileprivate var _status: BlueRefreshOssSoCredentialStatus? = nil
  fileprivate var _configuration: BlueOssSoConfiguration? = nil
}

public struct BlueRefreshOssSoCredentials {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var credentials: [BlueRefreshOssSoCredential] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension BlueDeviceType: @unchecked Sendable {}
extension BlueRefreshOssSoCredentialStatus: @unchecked Sendable {}
extension BlueI18n: @unchecked Sendable {}
extension BlueDeviceDetailsBluetooth: @unchecked Sendable {}
extension BlueDeviceDetailsUWB: @unchecked Sendable {}
extension BlueDeviceInfo: @unchecked Sendable {}
extension BlueDeviceInfo.OneOf_Details: @unchecked Sendable {}
extension BlueAccessCredential: @unchecked Sendable {}
extension BlueAccessCredentialList: @unchecked Sendable {}
extension BlueAccessDevice: @unchecked Sendable {}
extension BlueAccessDeviceList: @unchecked Sendable {}
extension BlueAccessObject: @unchecked Sendable {}
extension BlueAccessObjectList: @unchecked Sendable {}
extension BlueRefreshOssSoCredential: @unchecked Sendable {}
extension BlueRefreshOssSoCredentials: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension BlueDeviceType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "BluetoothDevice"),
    2: .same(proto: "UWBDevice"),
  ]
}

extension BlueRefreshOssSoCredentialStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "Succeeded"),
    2: .same(proto: "Failed"),
    3: .same(proto: "NotNeeded"),
    4: .same(proto: "Unsupported"),
  ]
}

extension BlueI18n: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueI18n"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "nfcWaitMessage"),
    2: .same(proto: "nfcOssSuccessReadConfigurationMessage"),
    3: .same(proto: "nfcOssSuccessUpdateConfigurationMessage"),
    4: .same(proto: "nfcOssSuccessClearEventsMessage"),
    5: .same(proto: "nfcOssSuccessIsProvisionedMessage"),
    6: .same(proto: "nfcOssSuccessProvisionMessage"),
    7: .same(proto: "nfcOssSuccessUnprovisionMessage"),
    8: .same(proto: "nfcOssSuccessFormatMessage"),
    9: .same(proto: "cmnCancelLabel"),
    10: .same(proto: "openViaOssTitle"),
    11: .same(proto: "openViaOssWaitMessage"),
    12: .same(proto: "openViaOssSuccessfulMessage"),
    13: .same(proto: "openViaOssUnsuccessfulMessage"),
  ]

  public var isInitialized: Bool {
    if self._nfcWaitMessage == nil {return false}
    if self._nfcOssSuccessReadConfigurationMessage == nil {return false}
    if self._nfcOssSuccessUpdateConfigurationMessage == nil {return false}
    if self._nfcOssSuccessClearEventsMessage == nil {return false}
    if self._nfcOssSuccessIsProvisionedMessage == nil {return false}
    if self._nfcOssSuccessProvisionMessage == nil {return false}
    if self._nfcOssSuccessUnprovisionMessage == nil {return false}
    if self._nfcOssSuccessFormatMessage == nil {return false}
    if self._cmnCancelLabel == nil {return false}
    if self._openViaOssTitle == nil {return false}
    if self._openViaOssWaitMessage == nil {return false}
    if self._openViaOssSuccessfulMessage == nil {return false}
    if self._openViaOssUnsuccessfulMessage == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._nfcWaitMessage) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._nfcOssSuccessReadConfigurationMessage) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._nfcOssSuccessUpdateConfigurationMessage) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._nfcOssSuccessClearEventsMessage) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._nfcOssSuccessIsProvisionedMessage) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._nfcOssSuccessProvisionMessage) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._nfcOssSuccessUnprovisionMessage) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._nfcOssSuccessFormatMessage) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self._cmnCancelLabel) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self._openViaOssTitle) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self._openViaOssWaitMessage) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self._openViaOssSuccessfulMessage) }()
      case 13: try { try decoder.decodeSingularStringField(value: &self._openViaOssUnsuccessfulMessage) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._nfcWaitMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._nfcOssSuccessReadConfigurationMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._nfcOssSuccessUpdateConfigurationMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._nfcOssSuccessClearEventsMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._nfcOssSuccessIsProvisionedMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._nfcOssSuccessProvisionMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._nfcOssSuccessUnprovisionMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._nfcOssSuccessFormatMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._cmnCancelLabel {
      try visitor.visitSingularStringField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._openViaOssTitle {
      try visitor.visitSingularStringField(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._openViaOssWaitMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 11)
    } }()
    try { if let v = self._openViaOssSuccessfulMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 12)
    } }()
    try { if let v = self._openViaOssUnsuccessfulMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 13)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueI18n, rhs: BlueI18n) -> Bool {
    if lhs._nfcWaitMessage != rhs._nfcWaitMessage {return false}
    if lhs._nfcOssSuccessReadConfigurationMessage != rhs._nfcOssSuccessReadConfigurationMessage {return false}
    if lhs._nfcOssSuccessUpdateConfigurationMessage != rhs._nfcOssSuccessUpdateConfigurationMessage {return false}
    if lhs._nfcOssSuccessClearEventsMessage != rhs._nfcOssSuccessClearEventsMessage {return false}
    if lhs._nfcOssSuccessIsProvisionedMessage != rhs._nfcOssSuccessIsProvisionedMessage {return false}
    if lhs._nfcOssSuccessProvisionMessage != rhs._nfcOssSuccessProvisionMessage {return false}
    if lhs._nfcOssSuccessUnprovisionMessage != rhs._nfcOssSuccessUnprovisionMessage {return false}
    if lhs._nfcOssSuccessFormatMessage != rhs._nfcOssSuccessFormatMessage {return false}
    if lhs._cmnCancelLabel != rhs._cmnCancelLabel {return false}
    if lhs._openViaOssTitle != rhs._openViaOssTitle {return false}
    if lhs._openViaOssWaitMessage != rhs._openViaOssWaitMessage {return false}
    if lhs._openViaOssSuccessfulMessage != rhs._openViaOssSuccessfulMessage {return false}
    if lhs._openViaOssUnsuccessfulMessage != rhs._openViaOssUnsuccessfulMessage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlueDeviceDetailsBluetooth: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueDeviceDetailsBluetooth"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "rssi"),
    2: .same(proto: "txPower"),
    3: .same(proto: "isIBeacon"),
  ]

  public var isInitialized: Bool {
    if self._rssi == nil {return false}
    if self._txPower == nil {return false}
    if self._isIbeacon == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._rssi) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._txPower) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._isIbeacon) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._rssi {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._txPower {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._isIbeacon {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueDeviceDetailsBluetooth, rhs: BlueDeviceDetailsBluetooth) -> Bool {
    if lhs._rssi != rhs._rssi {return false}
    if lhs._txPower != rhs._txPower {return false}
    if lhs._isIbeacon != rhs._isIbeacon {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlueDeviceDetailsUWB: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueDeviceDetailsUWB"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "notUsed"),
  ]

  public var isInitialized: Bool {
    if self._notUsed == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._notUsed) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._notUsed {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueDeviceDetailsUWB, rhs: BlueDeviceDetailsUWB) -> Bool {
    if lhs._notUsed != rhs._notUsed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlueDeviceInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueDeviceInfo"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "deviceType"),
    2: .same(proto: "deviceId"),
    3: .same(proto: "distanceMeters"),
    4: .same(proto: "manufacturerInfo"),
    5: .same(proto: "bluetooth"),
    6: .same(proto: "uwb"),
  ]

  public var isInitialized: Bool {
    if self._deviceType == nil {return false}
    if self._deviceID == nil {return false}
    if self._distanceMeters == nil {return false}
    if let v = self._manufacturerInfo, !v.isInitialized {return false}
    if let v = self.details, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._deviceType) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._deviceID) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self._distanceMeters) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._manufacturerInfo) }()
      case 5: try {
        var v: BlueDeviceDetailsBluetooth?
        var hadOneofValue = false
        if let current = self.details {
          hadOneofValue = true
          if case .bluetooth(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.details = .bluetooth(v)
        }
      }()
      case 6: try {
        var v: BlueDeviceDetailsUWB?
        var hadOneofValue = false
        if let current = self.details {
          hadOneofValue = true
          if case .uwb(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.details = .uwb(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._deviceType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._deviceID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._distanceMeters {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._manufacturerInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    switch self.details {
    case .bluetooth?: try {
      guard case .bluetooth(let v)? = self.details else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .uwb?: try {
      guard case .uwb(let v)? = self.details else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueDeviceInfo, rhs: BlueDeviceInfo) -> Bool {
    if lhs._deviceType != rhs._deviceType {return false}
    if lhs._deviceID != rhs._deviceID {return false}
    if lhs._distanceMeters != rhs._distanceMeters {return false}
    if lhs._manufacturerInfo != rhs._manufacturerInfo {return false}
    if lhs.details != rhs.details {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlueAccessCredential: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueAccessCredential"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "credentialId"),
    2: .same(proto: "credentialType"),
    3: .same(proto: "name"),
    4: .same(proto: "description"),
    5: .same(proto: "siteId"),
    6: .same(proto: "siteName"),
    7: .same(proto: "validFrom"),
    8: .same(proto: "validTo"),
    9: .same(proto: "validity"),
    10: .same(proto: "privateKey"),
    11: .same(proto: "receiverName"),
    12: .same(proto: "organisation"),
    13: .same(proto: "organisationName"),
  ]

  fileprivate class _StorageClass {
    var _credentialID: BlueCredentialId? = nil
    var _credentialType: BlueCredentialType? = nil
    var _name: String? = nil
    var _description_p: String? = nil
    var _siteID: Int32? = nil
    var _siteName: String? = nil
    var _validFrom: BlueLocalTimestamp? = nil
    var _validTo: BlueLocalTimestamp? = nil
    var _validity: BlueLocalTimestamp? = nil
    var _privateKey: Data? = nil
    var _receiverName: String? = nil
    var _organisation: String? = nil
    var _organisationName: String? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _credentialID = source._credentialID
      _credentialType = source._credentialType
      _name = source._name
      _description_p = source._description_p
      _siteID = source._siteID
      _siteName = source._siteName
      _validFrom = source._validFrom
      _validTo = source._validTo
      _validity = source._validity
      _privateKey = source._privateKey
      _receiverName = source._receiverName
      _organisation = source._organisation
      _organisationName = source._organisationName
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._credentialID == nil {return false}
      if _storage._credentialType == nil {return false}
      if _storage._siteID == nil {return false}
      if _storage._organisation == nil {return false}
      if let v = _storage._credentialID, !v.isInitialized {return false}
      if let v = _storage._validFrom, !v.isInitialized {return false}
      if let v = _storage._validTo, !v.isInitialized {return false}
      if let v = _storage._validity, !v.isInitialized {return false}
      return true
    }
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._credentialID) }()
        case 2: try { try decoder.decodeSingularEnumField(value: &_storage._credentialType) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._description_p) }()
        case 5: try { try decoder.decodeSingularInt32Field(value: &_storage._siteID) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._siteName) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._validFrom) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._validTo) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._validity) }()
        case 10: try { try decoder.decodeSingularBytesField(value: &_storage._privateKey) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._receiverName) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._organisation) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._organisationName) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._credentialID {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._credentialType {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._name {
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._description_p {
        try visitor.visitSingularStringField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._siteID {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._siteName {
        try visitor.visitSingularStringField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._validFrom {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._validTo {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._validity {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._privateKey {
        try visitor.visitSingularBytesField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._receiverName {
        try visitor.visitSingularStringField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._organisation {
        try visitor.visitSingularStringField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._organisationName {
        try visitor.visitSingularStringField(value: v, fieldNumber: 13)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueAccessCredential, rhs: BlueAccessCredential) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._credentialID != rhs_storage._credentialID {return false}
        if _storage._credentialType != rhs_storage._credentialType {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._description_p != rhs_storage._description_p {return false}
        if _storage._siteID != rhs_storage._siteID {return false}
        if _storage._siteName != rhs_storage._siteName {return false}
        if _storage._validFrom != rhs_storage._validFrom {return false}
        if _storage._validTo != rhs_storage._validTo {return false}
        if _storage._validity != rhs_storage._validity {return false}
        if _storage._privateKey != rhs_storage._privateKey {return false}
        if _storage._receiverName != rhs_storage._receiverName {return false}
        if _storage._organisation != rhs_storage._organisation {return false}
        if _storage._organisationName != rhs_storage._organisationName {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlueAccessCredentialList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueAccessCredentialList"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "credentials"),
  ]

  public var isInitialized: Bool {
    if !SwiftProtobuf.Internal.areAllInitialized(self.credentials) {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.credentials) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.credentials.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.credentials, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueAccessCredentialList, rhs: BlueAccessCredentialList) -> Bool {
    if lhs.credentials != rhs.credentials {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlueAccessDevice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueAccessDevice"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "deviceId"),
    2: .same(proto: "objectName"),
    3: .same(proto: "objectId"),
  ]

  public var isInitialized: Bool {
    if self._deviceID == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._deviceID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._objectName) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._objectID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._deviceID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._objectName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._objectID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueAccessDevice, rhs: BlueAccessDevice) -> Bool {
    if lhs._deviceID != rhs._deviceID {return false}
    if lhs._objectName != rhs._objectName {return false}
    if lhs._objectID != rhs._objectID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlueAccessDeviceList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueAccessDeviceList"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "devices"),
  ]

  public var isInitialized: Bool {
    if !SwiftProtobuf.Internal.areAllInitialized(self.devices) {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.devices) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.devices.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.devices, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueAccessDeviceList, rhs: BlueAccessDeviceList) -> Bool {
    if lhs.devices != rhs.devices {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlueAccessObject: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueAccessObject"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "_id"),
    2: .same(proto: "objectId"),
    3: .same(proto: "name"),
    4: .same(proto: "description"),
    5: .same(proto: "deviceIds"),
  ]

  public var isInitialized: Bool {
    if self._id == nil {return false}
    if self._objectID == nil {return false}
    if self._name == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._id) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._objectID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._description_p) }()
      case 5: try { try decoder.decodeRepeatedStringField(value: &self.deviceIds) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._id {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._objectID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._description_p {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    if !self.deviceIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.deviceIds, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueAccessObject, rhs: BlueAccessObject) -> Bool {
    if lhs._id != rhs._id {return false}
    if lhs._objectID != rhs._objectID {return false}
    if lhs._name != rhs._name {return false}
    if lhs._description_p != rhs._description_p {return false}
    if lhs.deviceIds != rhs.deviceIds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlueAccessObjectList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueAccessObjectList"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "objects"),
  ]

  public var isInitialized: Bool {
    if !SwiftProtobuf.Internal.areAllInitialized(self.objects) {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.objects) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.objects.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.objects, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueAccessObjectList, rhs: BlueAccessObjectList) -> Bool {
    if lhs.objects != rhs.objects {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlueRefreshOssSoCredential: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueRefreshOssSoCredential"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "credentialId"),
    2: .same(proto: "status"),
    3: .same(proto: "configuration"),
  ]

  public var isInitialized: Bool {
    if self._credentialID == nil {return false}
    if self._status == nil {return false}
    if let v = self._credentialID, !v.isInitialized {return false}
    if let v = self._configuration, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._credentialID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self._status) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._configuration) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._credentialID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._status {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._configuration {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueRefreshOssSoCredential, rhs: BlueRefreshOssSoCredential) -> Bool {
    if lhs._credentialID != rhs._credentialID {return false}
    if lhs._status != rhs._status {return false}
    if lhs._configuration != rhs._configuration {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlueRefreshOssSoCredentials: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueRefreshOssSoCredentials"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "credentials"),
  ]

  public var isInitialized: Bool {
    if !SwiftProtobuf.Internal.areAllInitialized(self.credentials) {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.credentials) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.credentials.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.credentials, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueRefreshOssSoCredentials, rhs: BlueRefreshOssSoCredentials) -> Bool {
    if lhs.credentials != rhs.credentials {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
