// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: BlueSDK.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum BlueDeviceType: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case bluetoothDevice // = 1
  case uwbdevice // = 2

  public init() {
    self = .bluetoothDevice
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 1: self = .bluetoothDevice
    case 2: self = .uwbdevice
    default: return nil
    }
  }

  public var rawValue: Int {
    switch self {
    case .bluetoothDevice: return 1
    case .uwbdevice: return 2
    }
  }

}

#if swift(>=4.2)

extension BlueDeviceType: CaseIterable {
  // Support synthesized by the compiler.
}

#endif  // swift(>=4.2)

public struct BlueI18n {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var nfcWaitMessage: String {
    get {return _nfcWaitMessage ?? "Waiting for transponder"}
    set {_nfcWaitMessage = newValue}
  }
  /// Returns true if `nfcWaitMessage` has been explicitly set.
  public var hasNfcWaitMessage: Bool {return self._nfcWaitMessage != nil}
  /// Clears the value of `nfcWaitMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcWaitMessage() {self._nfcWaitMessage = nil}

  public var nfcOssSuccessReadConfigurationMessage: String {
    get {return _nfcOssSuccessReadConfigurationMessage ?? "Configuration read successfully"}
    set {_nfcOssSuccessReadConfigurationMessage = newValue}
  }
  /// Returns true if `nfcOssSuccessReadConfigurationMessage` has been explicitly set.
  public var hasNfcOssSuccessReadConfigurationMessage: Bool {return self._nfcOssSuccessReadConfigurationMessage != nil}
  /// Clears the value of `nfcOssSuccessReadConfigurationMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcOssSuccessReadConfigurationMessage() {self._nfcOssSuccessReadConfigurationMessage = nil}

  public var nfcOssSuccessUpdateConfigurationMessage: String {
    get {return _nfcOssSuccessUpdateConfigurationMessage ?? "Configuration successfully updated"}
    set {_nfcOssSuccessUpdateConfigurationMessage = newValue}
  }
  /// Returns true if `nfcOssSuccessUpdateConfigurationMessage` has been explicitly set.
  public var hasNfcOssSuccessUpdateConfigurationMessage: Bool {return self._nfcOssSuccessUpdateConfigurationMessage != nil}
  /// Clears the value of `nfcOssSuccessUpdateConfigurationMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcOssSuccessUpdateConfigurationMessage() {self._nfcOssSuccessUpdateConfigurationMessage = nil}

  public var nfcOssSuccessClearEventsMessage: String {
    get {return _nfcOssSuccessClearEventsMessage ?? "Events successfully cleared"}
    set {_nfcOssSuccessClearEventsMessage = newValue}
  }
  /// Returns true if `nfcOssSuccessClearEventsMessage` has been explicitly set.
  public var hasNfcOssSuccessClearEventsMessage: Bool {return self._nfcOssSuccessClearEventsMessage != nil}
  /// Clears the value of `nfcOssSuccessClearEventsMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcOssSuccessClearEventsMessage() {self._nfcOssSuccessClearEventsMessage = nil}

  public var nfcOssSuccessIsProvisionedMessage: String {
    get {return _nfcOssSuccessIsProvisionedMessage ?? "Is already provisioned"}
    set {_nfcOssSuccessIsProvisionedMessage = newValue}
  }
  /// Returns true if `nfcOssSuccessIsProvisionedMessage` has been explicitly set.
  public var hasNfcOssSuccessIsProvisionedMessage: Bool {return self._nfcOssSuccessIsProvisionedMessage != nil}
  /// Clears the value of `nfcOssSuccessIsProvisionedMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcOssSuccessIsProvisionedMessage() {self._nfcOssSuccessIsProvisionedMessage = nil}

  public var nfcOssSuccessProvisionMessage: String {
    get {return _nfcOssSuccessProvisionMessage ?? "Successfully provisioned"}
    set {_nfcOssSuccessProvisionMessage = newValue}
  }
  /// Returns true if `nfcOssSuccessProvisionMessage` has been explicitly set.
  public var hasNfcOssSuccessProvisionMessage: Bool {return self._nfcOssSuccessProvisionMessage != nil}
  /// Clears the value of `nfcOssSuccessProvisionMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcOssSuccessProvisionMessage() {self._nfcOssSuccessProvisionMessage = nil}

  public var nfcOssSuccessUnprovisionMessage: String {
    get {return _nfcOssSuccessUnprovisionMessage ?? "Successfully unprovisioned"}
    set {_nfcOssSuccessUnprovisionMessage = newValue}
  }
  /// Returns true if `nfcOssSuccessUnprovisionMessage` has been explicitly set.
  public var hasNfcOssSuccessUnprovisionMessage: Bool {return self._nfcOssSuccessUnprovisionMessage != nil}
  /// Clears the value of `nfcOssSuccessUnprovisionMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcOssSuccessUnprovisionMessage() {self._nfcOssSuccessUnprovisionMessage = nil}

  public var nfcOssSuccessFormatMessage: String {
    get {return _nfcOssSuccessFormatMessage ?? "Transponder was successfully formatted"}
    set {_nfcOssSuccessFormatMessage = newValue}
  }
  /// Returns true if `nfcOssSuccessFormatMessage` has been explicitly set.
  public var hasNfcOssSuccessFormatMessage: Bool {return self._nfcOssSuccessFormatMessage != nil}
  /// Clears the value of `nfcOssSuccessFormatMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNfcOssSuccessFormatMessage() {self._nfcOssSuccessFormatMessage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _nfcWaitMessage: String? = nil
  fileprivate var _nfcOssSuccessReadConfigurationMessage: String? = nil
  fileprivate var _nfcOssSuccessUpdateConfigurationMessage: String? = nil
  fileprivate var _nfcOssSuccessClearEventsMessage: String? = nil
  fileprivate var _nfcOssSuccessIsProvisionedMessage: String? = nil
  fileprivate var _nfcOssSuccessProvisionMessage: String? = nil
  fileprivate var _nfcOssSuccessUnprovisionMessage: String? = nil
  fileprivate var _nfcOssSuccessFormatMessage: String? = nil
}

public struct BlueDeviceDetailsBluetooth {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var rssi: Int32 {
    get {return _rssi ?? 0}
    set {_rssi = newValue}
  }
  /// Returns true if `rssi` has been explicitly set.
  public var hasRssi: Bool {return self._rssi != nil}
  /// Clears the value of `rssi`. Subsequent reads from it will return its default value.
  public mutating func clearRssi() {self._rssi = nil}

  public var txPower: Int32 {
    get {return _txPower ?? 0}
    set {_txPower = newValue}
  }
  /// Returns true if `txPower` has been explicitly set.
  public var hasTxPower: Bool {return self._txPower != nil}
  /// Clears the value of `txPower`. Subsequent reads from it will return its default value.
  public mutating func clearTxPower() {self._txPower = nil}

  public var isIbeacon: Bool {
    get {return _isIbeacon ?? false}
    set {_isIbeacon = newValue}
  }
  /// Returns true if `isIbeacon` has been explicitly set.
  public var hasIsIbeacon: Bool {return self._isIbeacon != nil}
  /// Clears the value of `isIbeacon`. Subsequent reads from it will return its default value.
  public mutating func clearIsIbeacon() {self._isIbeacon = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _rssi: Int32? = nil
  fileprivate var _txPower: Int32? = nil
  fileprivate var _isIbeacon: Bool? = nil
}

public struct BlueDeviceDetailsUWB {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var notUsed: Bool {
    get {return _notUsed ?? false}
    set {_notUsed = newValue}
  }
  /// Returns true if `notUsed` has been explicitly set.
  public var hasNotUsed: Bool {return self._notUsed != nil}
  /// Clears the value of `notUsed`. Subsequent reads from it will return its default value.
  public mutating func clearNotUsed() {self._notUsed = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _notUsed: Bool? = nil
}

public struct BlueDeviceInfo {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var deviceType: BlueDeviceType {
    get {return _deviceType ?? .bluetoothDevice}
    set {_deviceType = newValue}
  }
  /// Returns true if `deviceType` has been explicitly set.
  public var hasDeviceType: Bool {return self._deviceType != nil}
  /// Clears the value of `deviceType`. Subsequent reads from it will return its default value.
  public mutating func clearDeviceType() {self._deviceType = nil}

  public var deviceID: String {
    get {return _deviceID ?? String()}
    set {_deviceID = newValue}
  }
  /// Returns true if `deviceID` has been explicitly set.
  public var hasDeviceID: Bool {return self._deviceID != nil}
  /// Clears the value of `deviceID`. Subsequent reads from it will return its default value.
  public mutating func clearDeviceID() {self._deviceID = nil}

  public var distanceMeters: Float {
    get {return _distanceMeters ?? 0}
    set {_distanceMeters = newValue}
  }
  /// Returns true if `distanceMeters` has been explicitly set.
  public var hasDistanceMeters: Bool {return self._distanceMeters != nil}
  /// Clears the value of `distanceMeters`. Subsequent reads from it will return its default value.
  public mutating func clearDistanceMeters() {self._distanceMeters = nil}

  public var manufacturerInfo: BlueBleManufacturerInfo {
    get {return _manufacturerInfo ?? BlueBleManufacturerInfo()}
    set {_manufacturerInfo = newValue}
  }
  /// Returns true if `manufacturerInfo` has been explicitly set.
  public var hasManufacturerInfo: Bool {return self._manufacturerInfo != nil}
  /// Clears the value of `manufacturerInfo`. Subsequent reads from it will return its default value.
  public mutating func clearManufacturerInfo() {self._manufacturerInfo = nil}

  public var details: BlueDeviceInfo.OneOf_Details? = nil

  public var bluetooth: BlueDeviceDetailsBluetooth {
    get {
      if case .bluetooth(let v)? = details {return v}
      return BlueDeviceDetailsBluetooth()
    }
    set {details = .bluetooth(newValue)}
  }

  public var uwb: BlueDeviceDetailsUWB {
    get {
      if case .uwb(let v)? = details {return v}
      return BlueDeviceDetailsUWB()
    }
    set {details = .uwb(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Details: Equatable {
    case bluetooth(BlueDeviceDetailsBluetooth)
    case uwb(BlueDeviceDetailsUWB)

    fileprivate var isInitialized: Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch self {
      case .bluetooth: return {
        guard case .bluetooth(let v) = self else { preconditionFailure() }
        return v.isInitialized
      }()
      case .uwb: return {
        guard case .uwb(let v) = self else { preconditionFailure() }
        return v.isInitialized
      }()
      }
    }

  #if !swift(>=4.1)
    public static func ==(lhs: BlueDeviceInfo.OneOf_Details, rhs: BlueDeviceInfo.OneOf_Details) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.bluetooth, .bluetooth): return {
        guard case .bluetooth(let l) = lhs, case .bluetooth(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.uwb, .uwb): return {
        guard case .uwb(let l) = lhs, case .uwb(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  public init() {}

  fileprivate var _deviceType: BlueDeviceType? = nil
  fileprivate var _deviceID: String? = nil
  fileprivate var _distanceMeters: Float? = nil
  fileprivate var _manufacturerInfo: BlueBleManufacturerInfo? = nil
}

#if swift(>=5.5) && canImport(_Concurrency)
extension BlueDeviceType: @unchecked Sendable {}
extension BlueI18n: @unchecked Sendable {}
extension BlueDeviceDetailsBluetooth: @unchecked Sendable {}
extension BlueDeviceDetailsUWB: @unchecked Sendable {}
extension BlueDeviceInfo: @unchecked Sendable {}
extension BlueDeviceInfo.OneOf_Details: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension BlueDeviceType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "BluetoothDevice"),
    2: .same(proto: "UWBDevice"),
  ]
}

extension BlueI18n: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueI18n"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "nfcWaitMessage"),
    2: .same(proto: "nfcOssSuccessReadConfigurationMessage"),
    3: .same(proto: "nfcOssSuccessUpdateConfigurationMessage"),
    4: .same(proto: "nfcOssSuccessClearEventsMessage"),
    5: .same(proto: "nfcOssSuccessIsProvisionedMessage"),
    6: .same(proto: "nfcOssSuccessProvisionMessage"),
    7: .same(proto: "nfcOssSuccessUnprovisionMessage"),
    8: .same(proto: "nfcOssSuccessFormatMessage"),
  ]

  public var isInitialized: Bool {
    if self._nfcWaitMessage == nil {return false}
    if self._nfcOssSuccessReadConfigurationMessage == nil {return false}
    if self._nfcOssSuccessUpdateConfigurationMessage == nil {return false}
    if self._nfcOssSuccessClearEventsMessage == nil {return false}
    if self._nfcOssSuccessIsProvisionedMessage == nil {return false}
    if self._nfcOssSuccessProvisionMessage == nil {return false}
    if self._nfcOssSuccessUnprovisionMessage == nil {return false}
    if self._nfcOssSuccessFormatMessage == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._nfcWaitMessage) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._nfcOssSuccessReadConfigurationMessage) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._nfcOssSuccessUpdateConfigurationMessage) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._nfcOssSuccessClearEventsMessage) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._nfcOssSuccessIsProvisionedMessage) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._nfcOssSuccessProvisionMessage) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._nfcOssSuccessUnprovisionMessage) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._nfcOssSuccessFormatMessage) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._nfcWaitMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._nfcOssSuccessReadConfigurationMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._nfcOssSuccessUpdateConfigurationMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._nfcOssSuccessClearEventsMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._nfcOssSuccessIsProvisionedMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._nfcOssSuccessProvisionMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._nfcOssSuccessUnprovisionMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._nfcOssSuccessFormatMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueI18n, rhs: BlueI18n) -> Bool {
    if lhs._nfcWaitMessage != rhs._nfcWaitMessage {return false}
    if lhs._nfcOssSuccessReadConfigurationMessage != rhs._nfcOssSuccessReadConfigurationMessage {return false}
    if lhs._nfcOssSuccessUpdateConfigurationMessage != rhs._nfcOssSuccessUpdateConfigurationMessage {return false}
    if lhs._nfcOssSuccessClearEventsMessage != rhs._nfcOssSuccessClearEventsMessage {return false}
    if lhs._nfcOssSuccessIsProvisionedMessage != rhs._nfcOssSuccessIsProvisionedMessage {return false}
    if lhs._nfcOssSuccessProvisionMessage != rhs._nfcOssSuccessProvisionMessage {return false}
    if lhs._nfcOssSuccessUnprovisionMessage != rhs._nfcOssSuccessUnprovisionMessage {return false}
    if lhs._nfcOssSuccessFormatMessage != rhs._nfcOssSuccessFormatMessage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlueDeviceDetailsBluetooth: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueDeviceDetailsBluetooth"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "rssi"),
    2: .same(proto: "txPower"),
    3: .same(proto: "isIBeacon"),
  ]

  public var isInitialized: Bool {
    if self._rssi == nil {return false}
    if self._txPower == nil {return false}
    if self._isIbeacon == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._rssi) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._txPower) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._isIbeacon) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._rssi {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._txPower {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._isIbeacon {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueDeviceDetailsBluetooth, rhs: BlueDeviceDetailsBluetooth) -> Bool {
    if lhs._rssi != rhs._rssi {return false}
    if lhs._txPower != rhs._txPower {return false}
    if lhs._isIbeacon != rhs._isIbeacon {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlueDeviceDetailsUWB: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueDeviceDetailsUWB"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "notUsed"),
  ]

  public var isInitialized: Bool {
    if self._notUsed == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._notUsed) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._notUsed {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueDeviceDetailsUWB, rhs: BlueDeviceDetailsUWB) -> Bool {
    if lhs._notUsed != rhs._notUsed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlueDeviceInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "BlueDeviceInfo"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "deviceType"),
    2: .same(proto: "deviceId"),
    3: .same(proto: "distanceMeters"),
    4: .same(proto: "manufacturerInfo"),
    5: .same(proto: "bluetooth"),
    6: .same(proto: "uwb"),
  ]

  public var isInitialized: Bool {
    if self._deviceType == nil {return false}
    if self._deviceID == nil {return false}
    if self._distanceMeters == nil {return false}
    if self._manufacturerInfo == nil {return false}
    if let v = self._manufacturerInfo, !v.isInitialized {return false}
    if let v = self.details, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._deviceType) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._deviceID) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self._distanceMeters) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._manufacturerInfo) }()
      case 5: try {
        var v: BlueDeviceDetailsBluetooth?
        var hadOneofValue = false
        if let current = self.details {
          hadOneofValue = true
          if case .bluetooth(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.details = .bluetooth(v)
        }
      }()
      case 6: try {
        var v: BlueDeviceDetailsUWB?
        var hadOneofValue = false
        if let current = self.details {
          hadOneofValue = true
          if case .uwb(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.details = .uwb(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._deviceType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._deviceID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._distanceMeters {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._manufacturerInfo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    switch self.details {
    case .bluetooth?: try {
      guard case .bluetooth(let v)? = self.details else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case .uwb?: try {
      guard case .uwb(let v)? = self.details else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlueDeviceInfo, rhs: BlueDeviceInfo) -> Bool {
    if lhs._deviceType != rhs._deviceType {return false}
    if lhs._deviceID != rhs._deviceID {return false}
    if lhs._distanceMeters != rhs._distanceMeters {return false}
    if lhs._manufacturerInfo != rhs._manufacturerInfo {return false}
    if lhs.details != rhs.details {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
